project:
  type: website
  output-dir: docs
  resources:
    - "images/"

execute:
  freeze: auto
  cache: true

website:
  title: "Jiahong's blog"
  description: "A daily summary"
  #site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sunjh22
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Bioinformatics"
        contents: posts/bioinfo
      - section: "Life & Recipes"
        contents: posts/life
      - section: "Daily summary"
        contents: posts/daily
format:
  html:
    theme: cosmo
        #- brand
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true

# Global settings for R code
knitr:
  opts_chunk:
    message: false
    warning: false
    fig.align: "center"
    fig.width: 8
    fig.height: 6
    dpi: 300
    dev: "svg"
