project:
  type: website
  output-dir: docs

website:
  #description: "A blog built with Quarto"
  #site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Jiahong's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sunjh22
      - icon: twitter
        href: https://twitter.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Bioinformatics"
        contents: posts/bioinfo
      - section: "Life & Recipes"
        contents: posts/life
format:
  html:
    theme: cosmo
        #- brand
    css: styles.css
    toc: true

